openapi: "3.0.2"

info:
  version: 0.3.0
  title: "twystd-uhppote-simulator"
  description: "REST API for the twystd UHPPOTE simulator command interface"
  license:
    name: "MIT"
    url: "https://github.com/twystd/uhppote-go/blob/master/LICENSE"
    
servers:    
  - url: "http://127.0.0.1:8080/uhppote"
  
tags:
  - name: "simulator"
    description: "UHPPOTE simulator command interface"

paths:
  /simulator:
    get:
      tags:
        - simulator
      summary: "Retrieves a list of active simulators"
      description: "Retrieves the list of simulated UHPPOTE devices"
      operationId: listDevices
      responses:
        '200':
          description: "List of simulated devices"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/DeviceList"        
        '405':
          description: "Invalid request"
        default:
          description: "Request failed"

    post:
      tags:
        - simulator
      summary: "Creates a new simulator device"
      description: "Creates a new simulator device. An existing device with the same device ID is not overwritten."
      operationId: createDevice
      requestBody:
        description: "Device ID and type"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewDevice"     
      responses:
        '200':
          description: "Device create request processed"
          headers:
            Location:
              schema:
                type: string
              description: "URL for created device"
        '405':
          description: "Invalid request"
        '500':
          description: "Internal system error"
        default:
          description: "Request failed"

  /simulator/{device-id}:
    delete:
      tags:
        - simulator
      summary: "Deletes a simulator device"
      description: "Removes all trace of a simulator device"
      operationId: deleteDevice
      parameters:
        - name: device-id
          in: path
          description: "Simulator device ID"
          required: true
          schema:
            type: integer
            format: uint64
            example: 753186420
      responses:
        '200':
          description: "Device deleted"
        '404':
          description: "No device with ID matching device-id"
        '500':
          description: "Internal system error"
        default:
          description: "Request failed"

  /simulator/{device-id}/swipe:
    post:
      tags:
        - simulator
      summary: "Simulates a card swipe on an access reader"
      description: "Simulates a card swipe on an access reader, generating an access event"
      operationId: swipeCard
      parameters:
        - name: device-id
          in: path
          description: "Simulator device ID"
          required: true
          schema:
            type: integer
            format: uint64
            example: 305419896
      requestBody:
        description: "Wiegand-26 access card details"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Swipe"     
      responses:
        '200':
          description: "Access granted/denied"
          headers:
            Location:
              schema:
                type: string
              description: "URL for swipe event"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Swiped"        
        '400':
          description: "Invalid request format"
        '404':
          description: "No device with ID matching device-id"
        '500':
          description: "Internal system error"
        default:
          description: "Request failed"

components:
  schemas:
    Device:
      required: 
        - device-id
        - device-type
        - uri
      properties:
        device-id:
          type: number
          format: uint32
          description: "Simulator device ID"
          example: 305419896
        device-type:  
          type: string
          format: string
          description: "UHPPOTE device type"
          example: "UT0311-L04"
        uri:  
          type: string
          format: URI
          description: "Base URI for the device"
          example: "/uhppote/simulator/305419896"
    DeviceList:
      required: 
        - devices
      properties:
        devices:
          type: array
          items:
            $ref: "#/components/schemas/Device"        
          description: "List of simulator devices"
    NewDevice:
      required: 
        - device-id
        - device-type
        - compressed
      properties:
        device-id:
          type: number
          format: uint32
          description: "Simulator device ID"
          example: 753186420
        device-type:  
          type: string
          format: "UTO311-L04"
          description: "UHPPOTE device type. Only UTO311-L04 is supported at present"
          example: "UT0311-L04"
        compressed:  
          type: boolean
          format: true/false
          description: "Persisted as gzipped file if true"
          example: false
    Swipe:
      required: 
        - door
        - card-number
      properties:
        door:
          type: number
          format: uint8
          description: "Door # [1..4]"
          example: 4
        card-number:  
          type: number
          format: uint32
          description: "Wiegand-26 card number"
          example: 65538
    Swiped:
      required: 
        - access-granted
        - door-opened
        - message
      properties:
        access-granted:
          type: boolean
          description: "true if access was granted"
        door-opened:
          type: boolean
          description: "true if door was opened"
        message:
          type: string
          description: "Display message"

