swagger: "2.0"
info:
  description: "REST API for the twystd UHPPOTE simulator"
  version: "1.0.0"
  title: "twyst-uhppote-simulator"
  license:
    name: "MIT"
    url: "https://github.com/twystd/uhppote-go/blob/master/LICENSE"
host: "127.0.0.1:8080"
basePath: "/uhppote"
tags:
- name: "simulator"
  description: "UHPPOTE simulator command interface"
schemes:
- "http"
paths:
  /simulator/{device-id}/swipe:
    post:
      tags:
      - "simulator"
      summary: "Simulates a card swipe on an access reader"
      description: "Simulates a card swipe on an access reader, generating an access event"
      operationId: "swipeCard"
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: "device-id"
        in: "path"
        description: "Simulator device ID e.g. 305419896"
        required: true
        type: "integer"
        format: "uint64"
      - name: "swipe"
        in: body
        description: "Wiegand-26 access card details"
        schema:
          type: object
          required:
            - swipe
          properties:
            swipe:
              $ref: "#/definitions/Swipe"        
      responses:
        200:
          description: "Access granted/denied"
          schema:
            $ref: "#/definitions/Swiped"        
        405:
          description: "Invalid request"
definitions:
  Swipe:
    type: "object"
    properties:
      door:
        type: "number"
        format: "uint8"
        description: "Door # [1..4]"
        example: 4
      card-number:
        type: number
        format: "uint32"
        description: "Wiegand-26 card number"
        example: 65538
  Swiped:
    type: "object"
    properties:
      granted:
        type: "boolean"
        description: "true if access was granted"
      message:
        type: "string"
        description: "Display message"

