name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Checkout uhppote-core
      run: git clone https://github.com/uhppoted/uhppote-core.git uhppote-core

    - name: Checkout uhppoted-api
      run: git clone https://github.com/uhppoted/uhppoted-api.git uhppoted-api

    - name: Checkout uhppote-simulator
      run: git clone https://github.com/uhppoted/uhppote-simulator.git uhppote-simulator

    - name: Checkout uhppote-cli
      run: git clone https://github.com/uhppoted/uhppote-cli.git uhppote-cli

    - name: Checkout uhppoted-rest
      run: git clone https://github.com/uhppoted/uhppoted-rest.git uhppoted-rest

    - name: Checkout uhppoted-mqtt
      run: git clone https://github.com/uhppoted/uhppoted-mqtt.git uhppoted-mqtt

    - name: Build
      run: make build-github
